version: '3.5'
  
services:
  keycloak:
    container_name: keycloak
    image: quay.io/keycloak/keycloak:21.0.1
    restart: unless-stopped
    ports: 
      - "8083:8080"
    # restart: on-failure
    volumes:
     - ./keycloak-data:/opt/keycloak/data
    environment: 
      KEYCLOAK_ADMIN: admin
      KEYCLOAK_ADMIN_PASSWORD: admin
      KEYCLOAK_LOGLEVEL: DEBUG
      ROOT_LOGLEVEL: DEBUG
    command: 
      - start-dev 
      - --import-realm 